# Generated by Django 2.2 on 2019-05-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varanus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='b8A',
            new_name='b8a',
        ),
    ]
